### ISSUE TITLE
access_token.refresh() unauthorized

### ISSUE THREAD

**Issue by matt-weale** [pinterest/api-quickstart#102]
I have a Python script that I am running to pull Ad and Campaign data from the Pinterest API. I am trying to refresh my `access_token` in the script but am getting an error. I am able to run the `python/scripts/refresh_access_token.py` without issue, however when I mimic the steps in my Python script I have an issue. Here is a code snippet and screenshot of the error. Please let me know if I can provide any additional context. Thanks.

```
api_config = ApiConfig(version=5)
# Setup access token
access_token = AccessToken(api_config, name='access_token_v5')
access_token.read()
access_token.refresh()
```
![Screenshot 2023-08-02 at 3 27 44 PM](https://github.com/pinterest/api-quickstart/assets/98363097/6b5ad2f8-66d3-4a82-b9c2-59e3ca4a774c)

**Comment by davidchaiken** [comment]
Hello! Glad to hear that `refresh_access_token` is working, because that means that the end-to-end system is working in general. I'll try to find some time to replicate the issue that you're seeing and figure out a fix.

**Comment by matt-weale** [comment]
Thanks for the quick response and I appreciate your help. Please let me know if there is anything I can do to help.

**Comment by davidchaiken** [comment]
Hello! I reproduced a similar looking problem by intentionally corrupting the refresh token in the file where it is stored.
```
$ ./scripts/refresh_access_token.py -a catest
Using application ID and secret from PINTEREST_APP_ID and PINTEREST_APP_SECRET.
read chaikenacm from /Users/dchaiken/code/api-quickstart/common/scripts/../oauth_tokens/catest.json
refreshing chaikenacm...
POST https://api.pinterest.com/v5/oauth/token
<Response [401]>
request failed with reason: Unauthorized
x-pinterest-rid: 1278171889818566
{'code': 283, 'message': 'The authorization grant is invalid'}
Traceback (most recent call last):
  File "/Users/dchaiken/code/api-quickstart/python/./scripts/refresh_access_token.py", line 55, in <module>
    main(sys.argv[1:])
  File "/Users/dchaiken/code/api-quickstart/python/./scripts/refresh_access_token.py", line 32, in main
    access_token.refresh()
  File "/Users/dchaiken/code/api-quickstart/python/src/access_token.py", line 189, in refresh
    unpacked = self.unpack(response)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dchaiken/code/api-quickstart/python/src/api_common.py", line 87, in unpack
    raise RuntimeError(status)
RuntimeError: request failed with reason: Unauthorized
```
Here are a few thoughts...

1. It probably won't fix the problem, but it would be helpful to update your fork of this repo to the main branch. (If you would prefer, I could do a formal release of the main branch (which I haven't done in a while).
2. It would help to be able to see the log that shows the error returned from the API. For example, `{'code': 283, 'message': 'The authorization grant is invalid'}` in the error above.
3. I wonder whether the error that you're experiencing has something to do with the way that the access token is originally created and stored along with the refresh token. The default location is at /common/oauth_tokens in this repo. You might want to have a look at the access_token_v5.json file that stores the access token and associated refresh token to make sure that it has all of the expected information.

If none of these thoughts help you, I'd like to figure out how to get more complete logs from your application (which is tricky, because we shouldn't be sending the actual tokens to each other).

**Comment by matt-weale** [comment]
Thanks for your help here, I was able to resolve the bug.

**Comment by matt-weale** [comment]
Thanks for your help, I was able to resolve.
