### ISSUE TITLE
Is it possible to use the Pinterest API from an client application that does not have a login?

### ISSUE THREAD

**Issue by matthewcummings** [pinterest/api-quickstart#107]
I want to leverage the API on schedule to analyze keyword trends so that I can adjust my Pinterest content accordingly. Is this use case supported? Also, is there a way to do this without going through the OAuth browser flow e.g. a service to service authentication flow?

**Comment by matthewcummings** [comment]
I might be mistaken but this example looks like exactly what I need but I'd like to avoid the browser auth part because I want to run my API queries on a cron-like schedule.

**Comment by davidchaiken** [comment]
Yes. This repo has code in the `access_token.js` and `access_token.py` files that reads and writes the tokens to the local file system in a configurable directory. You could manually generate an access token and refresh token, and then use the refresh token to get new tokens. The "continuous" option now allows the refresh token to be updated, so that you don't need to do another manual token generation in the future. If I were putting this kind of code into production at Pinterest, I would modify the code to use our secure secrets system to store the tokens instead of storing them in the local file system.

Is that all of the information that you need to get your use case working? I'm not exactly sure what you mean by "analyze keyword trends," but might be able to help if you tell me a bit more about what you're trying to achieve.

**Comment by matthewcummings** [comment]
I'm looking to write a simple app that surveys keyword metrics and trending keywords on Pinterest and use them to potentially inform us when it's time to adjust our content and marketing.

I've gone back and re-read the documentation. From what I can see, there is no way to use the Pinterest API without requesting access for a Pinterest App. I was hoping I could just create a (temporary is fine) API key just to get a feel for what the API can do.

**Comment by davidchaiken** [comment]
Yes, you need to register for a Pinterest App. Trial access should be very easy to get. If it's not, please let me know.

**Comment by davidchaiken** [comment]
Also... If you're interested in trying out the new [Trends API](https://developers.pinterest.com/docs/api/v5/#operation/trending_keywords/list), you can get information about applying for access [here](https://developers.pinterest.com/docs/new/about-beta-access/).

**Comment by davidchaiken** [comment]
I don't see any app requests that have been pending for more than a day. Maybe open a support ticket [here](https://help.pinterest.com/en/contact) to inquire about the status?

**Comment by matthewcummings** [comment]
Not sure why but I couldn't find my original request, so I submitted another which was approved today. Thanks @davidchaiken

**Comment by matthewcummings** [comment]
@davidchaiken my app mysteriously disappeared. I submitted a request for a new app. I opened a support ticket as well. If possible, I would like to try out this endpoint: https://api.pinterest.com/v5/trends/keywords/{region}/top/{trend_type} which is currently listed as "an alpha endpoint only available to select participants."

**Comment by davidchaiken** [comment]
Hi, Matthew. Thanks for opening the support ticket. I responded with a request for information via Zendesk. Let's follow-up there.
