### ISSUE TITLE
Split by APP_TYPE Only Returns 1 Row Per Day

### ISSUE THREAD

**Issue by patricker** [pinterest/api-quickstart#38]
I'm using the v5 API in Python to pull Account Analytics by day.

```
analytics_user = Analytics(0, api_config, access_token).last_30_days().split_field("APP_TYPE").get(advertiser_id)
```

This returns the summary data, plus 30 READY days and 1 PROCESSING day (today, so that makes sense). But the data is not "SPLIT" by APP_TYPE.  Inside of the daily data there is just a single Metric (I thought maybe there would be 3 entries under `metrics`, one for each day)

Looking at the log, here is the HTTP request made:

```
GET https://api.pinterest.com/v5/user_account/analytics?start_date=2021-12-12&end_date=2022-01-11&ad_account_id={AccountID}&split_field=APP_TYPE
<Response [200]>
```

I'd like to get the split by APP_TYPE, what am I missing here?

**Comment by davidchaiken** [comment]
Thanks for the feedback! Honestly, I implemented to the spec without understanding the semantics really well, so I'm going to have to spend a bit of time learning about our product to answer your question.

If the problem that you're seeing with split_field is due to a big in this quickstart, I'll fix it. If the problem is due to the implementation in Pinterest's API or back-end, I'll file an appropriate bug (and then maybe fix it myself if that makes sense). If it turns out that the analytics API is working as designed, I'll figure out how to let our product management team know that split-by-app-type isn't working as expected.

**Comment by davidchaiken** [comment]
Hi, @patricker. It turns out that split_field is a missing feature of the API. The feature is specified (so that it's in the API documentation) but not yet implemented. I'm double checking the status of the feature, and will reach out to you when it's ready to use. In the meantime, there's nothing that we can do in your code or this quickstart repo to get split_field to work.

**Comment by patricker** [comment]
@davidchaiken Do you know if the `app_types` filter is working? I could make... 3 calls to the API, one for each app_type.

**Comment by davidchaiken** [comment]
Sounds like a clever work-around, @patricker. The tech lead for Pinterest's API team just double-checked to make sure that the `app_types` filter is working, and we think that you're good to go. Please let us know if it works for you.

**Comment by davidchaiken** [comment]
@patricker Just wondering... Did the `app_types` filter work for you?

**Comment by patricker** [comment]
I just had time to test this today.

I ran three calls, and then compared the summary metrics with the v3 metrics available on the Analytics Web UI. While the numbers weren't identical, they were very close by device type.

```
    analytics_user_web = Analytics(0, api_config, access_token).last_30_days().app_types("web").get(advertiser_id)
    analytics_user_mobile = Analytics(0, api_config, access_token).last_30_days().app_types("mobile").get(advertiser_id)
    analytics_user_tablet = Analytics(0, api_config, access_token).last_30_days().app_types("tablet").get(advertiser_id)
```

I think this will be a good work around for now.

**Comment by davidchaiken** [comment]
Thanks for the update! It's good to hear that using the `app_types` filter works for you. I'll chat with folks on our API and analytics teams about whether:
1. We should investigate why v3 and v5 metrics by device type aren't identical.
2. How to document the filter workaround for `split_field` as part of the quickstart code in this repo.

**Comment by davidchaiken** [comment]
Pull request #40 captured this conversation in code.

**Comment by davidchaiken** [comment]
Hi, @patricker.

Circling back here... I just checked, and it looks like `split_field` is working now. Just wanted to let you know.

Best,
David
