### ISSUE TITLE
Problem generating API v3 tokens with Python scripts

### ISSUE THREAD

**Issue by Akiren** [pinterest/api-quickstart#48]
I can generate api v5 tokens with the python library no problem...
./scripts/get_access_token.py -w -s ads:read,pins:read,user_accounts:read,boards:read

If I attempt to generate v3 tokens with this 
 ./scripts/get_access_token.py -v 3 -a v3access -w -s read_pins,read_boards,read_user_followers

I get an invalid scopes requested even though all scopes are valid. Anyone else seen this issue? API v3 has analytics that v5 does not have.

**Comment by jquittograham** [comment]
Hello @Akiren, 

Thank you for your feedback! To clarify, newly created apps work exclusively with v5, since v3 is on track to be deprecated. The v3 scripts will only work if you have a legacy application that was given v3 access.

If you happen to have an application that has v3 access, then you can provide us with your app id and our team can investigate this issue further.

Thanks again!

**Comment by Luttik** [comment]
@jquittograham We should still be able to use v4 right? which also uses the tokens from v3 if I understand it correctly? v5 is still in bèta and as far as I can tell the `/ad_groups/analytics` endpoint doesn't ever return any data. So we are still confined to v4 with regards to analytics.

**Comment by jquittograham** [comment]
Hello @Akiren,

I just want to let you know again that we appreciate your feedback. We are going to close this issue, but feel free to comment or re-open if you have any more questions regarding our API.
