### ISSUE TITLE
Pins are private

### ISSUE THREAD

**Issue by abdouhl** [pinterest/api-quickstart#52]
When I create a pin the pin appears for me but not for other users

**Comment by davidchaiken** [comment]
Thanks for the question and sorry for the delay in our response, @abdouhl.

It's likely that your app has been granted Trial Access but not yet Standard Access. [This page](https://developers.pinterest.com/docs/api/v5/#tag/Getting-access) on the developers.pinterest.com describes the difference between these levels of access, including this note about the visibility of pins for Trial Access:
> Writing standard Pins: Yes - visible only to the user who creates them.

The idea is to allow applications with trial access to operate in a "sandbox" mode, so that developers can try out the API without "going live." Please see the section on [Requesting Standard Access](https://developers.pinterest.com/docs/api/v5/#section/Requesting-Standard-Access) for information on how to upgrade from Trial to Standard Access.
